name: Build Arm32v7 Image
on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: superng6/aria2
              platform: linux/arm/v7
              tag: arm32v7-latest
              dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
              dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}